<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="polet" nsURI="platform:/plugin/TDT4250Project.polet/model/polet.ecore"
    nsPrefix="polet">
  <eClassifiers xsi:type="ecore:EClass" name="Categories">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Products" upperBound="-1"
        eType="#//Product" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alcoholContents" upperBound="-1"
        eType="#//AlcoholContent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" upperBound="-1"
        eType="#//Country" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Prices" upperBound="-1"
        eType="#//Price" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productTypes" upperBound="-1"
        eType="#//ProductType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="volumes" upperBound="-1"
        eType="#//Volume" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Price">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="salesPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alcoholContent" eType="#//AlcoholContent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="price" eType="#//Price"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" eType="#//Country"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productType" eType="#//ProductType"
        eOpposite="#//ProductType/products"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Volume" eType="#//Volume"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alcoholPerKrone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kronePerVolume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlcoholContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percent" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Country">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="countryId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" ordered="false"
        upperBound="-1" eType="#//Region" containment="true" resolveProxies="false"
        eOpposite="#//Region/country"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regionId" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" eType="#//Country"
        eOpposite="#//Country/regions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produces" upperBound="-1"
        eType="#//ProductType" eOpposite="#//ProductType/producedIn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productTypeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productTypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producedIn" upperBound="-1"
        eType="#//Region" eOpposite="#//Region/produces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//Product" eOpposite="#//Product/productType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Volume">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="liters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
